services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: siteheater_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-siteheater}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-siteheater}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - siteheater_network

  # SiteHeater Application
  app:
    build: .
    container_name: siteheater_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      - siteheater_network
    command: python -m app.main

  # Database Backup Service
  backup:
    image: postgres:15-alpine
    container_name: siteheater_backup
    restart: "no" # Запускается только по cron или вручную
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-siteheater}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-siteheater_password}
      POSTGRES_DB: ${POSTGRES_DB:-siteheater}
      POSTGRES_HOST: postgres
      BACKUP_GITHUB_REPO: ${BACKUP_GITHUB_REPO}
      BACKUP_GITHUB_TOKEN: ${BACKUP_GITHUB_TOKEN}
      BACKUP_GITHUB_BRANCH: ${BACKUP_GITHUB_BRANCH:-main}
      BACKUP_ENCRYPTION_KEY: ${BACKUP_ENCRYPTION_KEY}
    volumes:
      - ./scripts:/scripts
      - backup_data:/app/backups
    networks:
      - siteheater_network
    entrypoint: /bin/sh
    command: -c "apk add --no-cache git openssl bash && /scripts/backup_db.sh"

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  backup_data:
    driver: local

networks:
  siteheater_network:
    driver: bridge
    internal: true
